export const USER_ACTIONS = {   
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SIGNUP: 'SIGNUP',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  DEACTIVATE_ACCOUNT: 'DEACTIVATE_ACCOUNT',
} as const

